"""add_security_blacklist

Revision ID: 6eea4bc67ecd
Revises: f4ae4e825aed
Create Date: 2026-01-30 21:49:06.445430

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


_ENUM_NAMES = (
    "market_kind_enum",
    "market_result_enum",
    "price_side_enum",
    "score_component_enum",
    "task_type_enum",
)
_ENUMS = [globals().get(name) for name in _ENUM_NAMES]


def _create_enums(bind) -> None:
    for enum in (e for e in _ENUMS if e is not None):
        try:
            enum.create(bind, checkfirst=True)
        except AttributeError:
            continue


def _drop_enums(bind) -> None:
    for enum in (e for e in reversed(_ENUMS) if e is not None):
        try:
            enum.drop(bind, checkfirst=True)
        except AttributeError:
            continue


# revision identifiers, used by Alembic.
revision = '6eea4bc67ecd'
down_revision = 'f4ae4e825aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    _create_enums(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for the blacklist entry'),
    sa.Column('identifier', sa.String(length=64), nullable=False, comment='The blacklisted identifier (hotkey SS58 address or IP address)'),
    sa.Column('identifier_type', sa.String(length=16), nullable=False, comment="Type of identifier: 'hotkey' or 'ip'"),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='Human-readable reason for blacklisting'),
    sa.Column('failure_type', sa.String(length=32), nullable=True, comment='The primary failure type that triggered blacklisting'),
    sa.Column('failure_count', sa.Integer(), nullable=False, comment='Total number of failures before blacklisting'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Optional JSON metadata (last IPs seen, failure history, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the entry was created (UTC)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the ban expires (NULL = permanent)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_blacklist')),
    sa.UniqueConstraint('identifier', 'identifier_type', name='uq_security_blacklist_identifier')
    )
    op.create_index('ix_security_blacklist_expires', 'security_blacklist', ['expires_at'], unique=False, postgresql_where='expires_at IS NOT NULL')
    op.create_index('ix_security_blacklist_identifier', 'security_blacklist', ['identifier'], unique=False)
    op.create_index('ix_security_blacklist_type', 'security_blacklist', ['identifier_type'], unique=False)
    op.drop_constraint(op.f('fk_miner_market_stats_miner'), 'miner_market_stats', type_='foreignkey')
    op.create_foreign_key('fk_miner_market_stats_miner', 'miner_market_stats', 'miner', ['miner_id', 'miner_hotkey'], ['miner_id', 'hotkey'], ondelete='CASCADE')
    op.alter_column('miner_rolling_score', 'score_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Version number for cross-validator consensus',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_miner_rolling_score_miner'), 'miner_rolling_score', type_='foreignkey')
    op.create_foreign_key('fk_miner_rolling_score_miner', 'miner_rolling_score', 'miner', ['miner_id', 'miner_hotkey'], ['miner_id', 'hotkey'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_miner_submission_miner'), 'miner_submission', type_='foreignkey')
    op.create_foreign_key('fk_miner_submission_miner', 'miner_submission', 'miner', ['miner_id', 'miner_hotkey'], ['miner_id', 'hotkey'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_miner_submission_miner', 'miner_submission', type_='foreignkey')
    op.create_foreign_key(op.f('fk_miner_submission_miner'), 'miner_submission', 'miner', ['miner_id', 'miner_hotkey'], ['miner_id', 'hotkey'])
    op.drop_constraint('fk_miner_rolling_score_miner', 'miner_rolling_score', type_='foreignkey')
    op.create_foreign_key(op.f('fk_miner_rolling_score_miner'), 'miner_rolling_score', 'miner', ['miner_id', 'miner_hotkey'], ['miner_id', 'hotkey'])
    op.alter_column('miner_rolling_score', 'score_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_comment='Version number for cross-validator consensus',
               existing_nullable=False)
    op.drop_constraint('fk_miner_market_stats_miner', 'miner_market_stats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_miner_market_stats_miner'), 'miner_market_stats', 'miner', ['miner_id', 'miner_hotkey'], ['miner_id', 'hotkey'])
    op.drop_index('ix_security_blacklist_type', table_name='security_blacklist')
    op.drop_index('ix_security_blacklist_identifier', table_name='security_blacklist')
    op.drop_index('ix_security_blacklist_expires', table_name='security_blacklist', postgresql_where='expires_at IS NOT NULL')
    op.drop_table('security_blacklist')
    # ### end Alembic commands ###
    bind = op.get_bind()
    _drop_enums(bind)
